In [1]:
%matplotlib inline
from matplotlib import pyplot as plt
import seaborn as sns

In [2]:
import antipackage
from github.ellisonbg.misc import vizarray as va

ImportError: cannot import name 'urlretrieve'

In [3]:
import numpy as np

In [4]:
data = [0,2,4,6]
a = np.array(data)

In [5]:
type(a)

numpy.ndarray

In [6]:
a

array([0, 2, 4, 6])

In [7]:
va.vizarray(a)

NameError: name 'va' is not defined

In [8]:
a.shape

(4,)

In [9]:
a.ndim

1

In [10]:
a.size

4

In [11]:
a.nbytes

32

In [12]:
a.dtype

dtype('int64')

In [13]:
data = [[0.0,2.0,4.0,6.0],[1.0,3.0,5.0,7.0]]
b=np.array(data)

In [14]:
b

array([[ 0.,  2.,  4.,  6.],
       [ 1.,  3.,  5.,  7.]])

In [18]:
c=np.arange(0,10,1/2)
c

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [19]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [21]:
np.ones_like(b)

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [23]:
a=np.zeros((3,3))
a
a.fill(4)
a

array([[ 4.,  4.,  4.],
       [ 4.,  4.,  4.],
       [ 4.,  4.,  4.]])

In [24]:
a= np.random.rand(10,10)

In [25]:
a

array([[ 0.21260933,  0.36850568,  0.98373757,  0.73654111,  0.29787282,
         0.29498827,  0.1642692 ,  0.47008893,  0.4459253 ,  0.91052039],
       [ 0.36046258,  0.36707947,  0.53463806,  0.57771534,  0.89249617,
         0.03224588,  0.08706301,  0.60288941,  0.50333265,  0.58346774],
       [ 0.90242326,  0.13867048,  0.73991578,  0.86904036,  0.98618508,
         0.34528735,  0.55457359,  0.84639596,  0.82006673,  0.96750102],
       [ 0.82893244,  0.65762741,  0.79273373,  0.39171631,  0.87930283,
         0.0062005 ,  0.38699974,  0.6621825 ,  0.64933225,  0.82022167],
       [ 0.27746891,  0.10094723,  0.4096463 ,  0.61247835,  0.12174885,
         0.34851475,  0.4677433 ,  0.31406085,  0.06445315,  0.80819758],
       [ 0.6222204 ,  0.75990162,  0.23574997,  0.78686092,  0.00980916,
         0.34595274,  0.82926038,  0.24160671,  0.87293508,  0.627491  ],
       [ 0.83398449,  0.7466057 ,  0.36806319,  0.78497155,  0.42252504,
         0.21392195,  0.37950074,  0.78894198

In [27]:
a[0,0]

0.21260933179616037

In [28]:
a[1,0]

0.36046258458304681

In [29]:
a[1,:]

array([ 0.36046258,  0.36707947,  0.53463806,  0.57771534,  0.89249617,
        0.03224588,  0.08706301,  0.60288941,  0.50333265,  0.58346774])

In [30]:
a[:,1]

array([ 0.36850568,  0.36707947,  0.13867048,  0.65762741,  0.10094723,
        0.75990162,  0.7466057 ,  0.17385461,  0.12909695,  0.89996236])

In [ ]:
ages = np.array([23,56,67,89,23,56,27,12,8,72])
genders = np.array(['m','m','f','f',])